# Generated by Django 3.2.8 on 2022-02-07 08:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=255, verbose_name='888 888 8888')),
                ('message', models.TextField(verbose_name='Xabar matni')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='contes/images/banner/', verbose_name='Banner Uchun Rasm')),
                ('card_image', models.ImageField(upload_to='contes/images/card/', verbose_name='Card Uchun Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('language', models.CharField(max_length=100, verbose_name='Qaysi Tilda')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('date', models.CharField(default='2022.02.25', max_length=255, verbose_name='Sana')),
                ('time', models.CharField(max_length=255, verbose_name='Vaqt')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Musobaqalar',
                'verbose_name_plural': 'Musobaqa',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='contes/images/banner/', verbose_name='Banner Uchun Rasm')),
                ('card_image', models.ImageField(upload_to='contes/images/card/', verbose_name='Card Uchun Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('date', models.CharField(default='2022.02.25', max_length=255, verbose_name='Sana')),
                ('time', models.CharField(max_length=255, verbose_name='Vaqt')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Tadbirlar',
                'verbose_name_plural': 'Tadbir',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('img', models.ImageField(upload_to='history_images/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Rasmlar',
                'verbose_name_plural': 'Rasm',
            },
        ),
        migrations.CreateModel(
            name='WhoIsForEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='event_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbir kimlar uchun',
                'verbose_name_plural': 'Tadbir kim uchun',
            },
        ),
        migrations.CreateModel(
            name='WhoIsForContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hackathon_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Hackathon kimlar uchun',
                'verbose_name_plural': 'Hackathon kim uchun',
            },
        ),
        migrations.CreateModel(
            name='WhatTookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='event_took_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbirdan nima olasiz',
                'verbose_name_plural': 'Tadbirdan nimalar olasiz',
            },
        ),
        migrations.CreateModel(
            name='WhatTookContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hackhathon_took_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Hackathon nima olasiz',
                'verbose_name_plural': 'Hackathon nimalar olasiz',
            },
        ),
        migrations.CreateModel(
            name='UsefullIconEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbir icons',
                'verbose_name_plural': 'Tadbir icons',
            },
        ),
        migrations.CreateModel(
            name='UsefullIconContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Musobaqa icons',
                'verbose_name_plural': 'Musobaqa icon',
            },
        ),
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, verbose_name='Vaqt')),
                ('why_text', models.CharField(max_length=255, verbose_name='Nima boladi')),
                ('left', models.BooleanField(verbose_name='Chap tomonga qoshish')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbir vaqt bolimlari',
                'verbose_name_plural': 'Tadbir vaqt bolimi',
            },
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, verbose_name='Vaqt')),
                ('why_text', models.CharField(max_length=255, verbose_name='Nima boladi')),
                ('left', models.BooleanField(verbose_name='Chap tomonga qoshish')),
                ('which_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Musobaqa vaqt bolimlari',
                'verbose_name_plural': 'Musobaqa vaqt bolimi',
            },
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('images', models.ManyToManyField(to='main.Images', verbose_name='Rasmlar')),
            ],
            options={
                'verbose_name': 'Oldingi Musobaqadan eslatmalar',
                'verbose_name_plural': 'Oldingi Musobaqadan eslatma',
            },
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('experience', models.CharField(max_length=255, verbose_name='Tajribangiz necha oy/yil ?')),
                ('phone', models.CharField(max_length=255, verbose_name='888 888 888')),
                ('about', models.TextField(verbose_name="O'zingiz haqingizda qisqacha ...")),
                ('which_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbir Registeratsiyalar',
                'verbose_name_plural': 'Tadbir Registeratsiya',
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('phone', models.CharField(max_length=255, verbose_name='888 888 888')),
                ('about', models.TextField(verbose_name="O'zingiz haqingizda qisqacha ...")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Tadbir Savollari',
                'verbose_name_plural': 'Tadbir Savoli',
            },
        ),
        migrations.CreateModel(
            name='ContestRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('experience', models.CharField(max_length=255, verbose_name='Tajribangiz necha oy/yil ?')),
                ('phone', models.CharField(max_length=255, verbose_name='888 888 888')),
                ('about', models.TextField(verbose_name="O'zingiz haqingizda qisqacha ...")),
                ('which_contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Musobaqa Registeratsiyalar',
                'verbose_name_plural': 'Musobaqa Registeratsiya',
            },
        ),
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('phone', models.CharField(max_length=255, verbose_name='888 888 888')),
                ('about', models.TextField(verbose_name="O'zingiz haqingizda qisqacha ...")),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
            ],
            options={
                'verbose_name': 'Tadbir Savollari',
                'verbose_name_plural': 'Tadbir Savoli',
            },
        ),
    ]
