# Generated by Django 3.2.8 on 2022-02-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestquestion',
            options={'verbose_name': 'Musobaqa Savollari', 'verbose_name_plural': 'Musobaqa Savoli'},
        ),
        migrations.AlterModelOptions(
            name='whattookcontest',
            options={'verbose_name': 'Musobaqa nima olasiz', 'verbose_name_plural': 'Musobaqa nimalar olasiz'},
        ),
        migrations.AlterModelOptions(
            name='whoisforcontest',
            options={'verbose_name': 'Musobaqa kimlar uchun', 'verbose_name_plural': 'Musobaqa kim uchun'},
        ),
    ]
